<a href="https://colab.research.google.com/github/gimquokka/ML/blob/master/Multi_neuron_nn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Trainin sigle Perceptron Neural network with multi figure and bias⭐️**

In [0]:
import numpy as np

## Initialize parameter!

In [0]:
#Training input value
#figure_set.shape = (6, 4)
figure_set = np.array([[0, 1, 0, 1], [1, 1, 1, 1],[1, 0, 1, 1], [1, 1, 0, 1], [1, 1, 0, 0], [0, 0, 0, 0]])

#Training labeled value
#labels.shape = (6, 1)
labels = np.array([[1, 1, 0, 1, 1, 0]]).reshape(6, 1)

#Give seed to random to get same random value for every iteration
np.random.seed(1)

weights = np.random.rand(4, 1)

bias = np.random.rand(1)

learning_rate = 0.1

## Sigmoid and it's derivative

In [0]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
  return sigmoid(x)/(1-sigmoid(x))

## Cost_function

In [33]:
iter_num = 20000
for iteration_num in range(iter_num):
# Feeedforward propagation
  # Feedforward step 1
  XW = np.dot(figure_set, weights)+bias
  
  # Feedforwaed step 2
  z = sigmoid(XW)
  
#Gradient decent(GD)
  # BP step 1
  err  = z - labels
  J = np.sum(np.square(err))
  
  #BP step 2
  dcost_over_dpred = err
  # print('dcost_over_dpred.shape', dcost_over_dpred.shape)
  
  dpred_over_dz = sigmoid_derivative(z)
  # print('dpred_over_dz.shape', dpred_over_dz.shape)

  dz_over_dw = figure_set
  # print('dz_over_dw.shape', dz_over_dw.shape)

  dcost_over_dz = dcost_over_dpred*dpred_over_dz

  if (iteration_num%1000) == 0:
    print(iteration_num + 1,'th', 'weight \n', weights)
    print('bias is\n', bias)
    print('predict output is \n', z,)
    print('labeled output is \n', labels)
    print('Cost function val(J): ', np.sum(np.square(err)))
    

  weights -= learning_rate*np.dot(dz_over_dw.T, dcost_over_dz)
  
  for bias_adjustment in dcost_over_dz:
    bias -= learning_rate*bias_adjustment

from notebook.services.config import ConfigManager
cm = ConfigManager().update('notebook', {'limit_output': 100})

1 th weight 
 [[ 1.33186716]
 [12.41657489]
 [-2.66947425]
 [ 1.31935845]]
bias is
 [-5.59702351]
predict output is 
 [[0.99970813]
 [0.99888891]
 [0.0036286 ]
 [0.99992293]
 [0.99971176]
 [0.00369518]]
labeled output is 
 [[1]
 [1]
 [0]
 [1]
 [1]
 [0]]
Cost function val(J):  2.8229863782113907e-05
1001 th weight 
 [[ 1.36441245]
 [12.84564357]
 [-2.72476239]
 [ 1.35274861]]
bias is
 [-5.82446095]
predict output is 
 [[0.99976925]
 [0.99910123]
 [0.00292345]
 [0.99994103]
 [0.99977192]
 [0.00294569]]
labeled output is 
 [[1]
 [1]
 [0]
 [1]
 [1]
 [0]]
Cost function val(J):  1.8140221751528062e-05
2001 th weight 
 [[ 1.39057365]
 [13.19668689]
 [-2.76921416]
 [ 1.37955116]]
bias is
 [-6.01027933]
predict output is 
 [[0.99980956]
 [0.99924446]
 [0.00244962]
 [0.99995259]
 [0.99981164]
 [0.0024474 ]]
labeled output is 
 [[1]
 [1]
 [0]
 [1]
 [1]
 [0]]
Cost function val(J):  1.2635250219154887e-05
3001 th weight 
 [[ 1.41239776]
 [13.49380237]
 [-2.8063045 ]
 [ 1.40188564]]
bias is
 [-6.167