<a href="https://colab.research.google.com/github/gimquokka/ML/blob/master/Sigle_perceptron_with_aggregative_derivative.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic Neural Network🍋

In [0]:
import numpy as np

## Sigmoid Function

In [0]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
  return x*(1-x)

## Initialize status

In [0]:
training_input = np.array([[0, 0, 1], [1,1,1], [1, 0, 1],[0,1,1]])

training_output =np.transpose(np.array([[0,1, 1, 0]]))
rg = np.random.default_rng(1)

## Test - Feed Forward Propagation

In [0]:
i = training_input
w = synaptic_weights
# Print Parameters
print('Training input data is')
print(i, '\n')
print('Initial Weight is')
print(w, '\n')

nn_output = sigmoid(np.dot(i, w))
print('Result output is')
print(nn_output)

Training input data is
[[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]] 

Initial Weight is
[[ 7.26592351]
 [-0.22360321]
 [-3.41412902]] 

Result output is
[[0.0318568 ]
 [0.97412321]
 [0.97920024]
 [0.02563738]]


## Training and Back Propargation!💫

In [0]:
itertaion_number = 10000
# Generate random number for asymmetric initialization of weight
synaptic_weights = 2*rg.random((3, 1)) - 1

# Trainning process
for i in range(itertaion_number):
  # Feed Forward Propagation
  nn_output = sigmoid(np.dot(training_input, synaptic_weights))
  # Get error
  err = training_output - nn_output # dim = 4 x 1

  # Backpropagation
  # Find the adjustment value for training synaptic_weight
  adjustments = np.dot(training_input.T, err*sigmoid_derivative(nn_output)) # dim(4 x 1) * dim(4 x 1) = dim(4 x 1)
  
  synaptic_weights += adjustments
  
  # Print parameters only at some point
  if i in [1, 10, 100, 1000, 9999]:
    print('i = ', i)
    print('error \n', err)
    print('adjustment \n', adjustments)
    print('synaptic_weights \n', synaptic_weights)
    # dt = {'names':['ID', 'Ring', '123', '412421'], 'formats':[float, float, float, float]} => Try to give name for output table
    structured_comparison = np.column_stack((training_input, nn_output))
    print('training_input and nn_output \n',structured_comparison, '\n\n')

i =  1
error 
 [[-0.37900081]
 [ 0.53813707]
 [ 0.671396  ]
 [-0.51696078]]
adjustment 
 [[0.28187726]
 [0.0046601 ]
 [0.06358445]]
synaptic_weights 
 [[ 0.06116294]
 [ 0.5663207 ]
 [-0.43020699]]
training_input and nn_output 
 [[0.         0.         1.         0.37900081]
 [1.         1.         1.         0.46186293]
 [1.         0.         1.         0.328604  ]
 [0.         1.         1.         0.51696078]] 


i =  10
error 
 [[-0.33558829]
 [ 0.26906226]
 [ 0.31080812]
 [-0.38225794]]
adjustment 
 [[ 0.11949297]
 [-0.0373493 ]
 [-0.04559791]]
synaptic_weights 
 [[ 1.59885386]
 [ 0.16569224]
 [-0.72861483]]
training_input and nn_output 
 [[0.         0.         1.         0.33558829]
 [1.         1.         1.         0.73093774]
 [1.         0.         1.         0.68919188]
 [0.         1.         1.         0.38225794]] 


i =  100
error 
 [[-0.1120736 ]
 [ 0.09076056]
 [ 0.07436044]
 [-0.09221287]]
adjustment 
 [[ 0.01260814]
 [-0.00022927]
 [-0.00626376]]
synaptic_weights 
 