<a href="https://colab.research.google.com/github/gimquokka/ML/blob/master/Pytorch_Docs_AUTOGRAD_AUTOMATIC_DIFFERENTIATION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# AUTOGRAD: AUTOMATIC DIFFERENTIATION

## Tensor

In [1]:
import torch

In [4]:
x = torch.ones(3, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)


In [5]:
y = x + 10
print(y)

tensor([[11., 11.],
        [11., 11.],
        [11., 11.]], grad_fn=<AddBackward0>)


In [10]:
print(y.grad_fn)

In [13]:
z = y*y
out = z.mean()

print(z)
print(out)

tensor([[121., 121.],
        [121., 121.],
        [121., 121.]], grad_fn=<MulBackward0>)
tensor(121., grad_fn=<MeanBackward0>)


In [22]:
a = torch.randn(2, 2)
a = a*a
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a)
print(b)
print(b.sum())
print(b.grad_fn)

False
True
tensor([[9.7295e-01, 5.3858e-03],
        [1.0405e+00, 9.2645e-07]], grad_fn=<MulBackward0>)
tensor(2.0189, grad_fn=<SumBackward0>)


## Gradients

In [25]:
out.backward()

In [26]:
print(x.grad)

tensor([[3.6667, 3.6667],
        [3.6667, 3.6667],
        [3.6667, 3.6667]])


In [30]:
print(y.retain_grad())

None


In [66]:
x = torch.randn(2,2, requires_grad=True)

y = x*15

print(y)

tensor([[ 2.9872,  5.6401],
        [ 9.0412, -6.7844]], grad_fn=<MulBackward0>)


In [73]:
x = torch.randn(2,2, requires_grad=True)

y = x**3

print(x)
# ------------------------------------------------------------
v = torch.tensor([[1, 2],[1, 4]], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([[0.8468, 1.2747],
        [0.0539, 0.2396]], requires_grad=True)
tensor([[2.1510e+00, 9.7487e+00],
        [8.7195e-03, 6.8905e-01]])


In [72]:
print(x.requires_grad)
print((x*x*x).requires_grad)

with torch.no_grad():
  print((x**3).requires_grad)

True
True
False


In [75]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)
