<a href="https://colab.research.google.com/github/gimquokka/ML/blob/master/Pytorch_Docs_WHAT_IS_PYTORCH%3F.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# WHAT IS PYTORCH?

## Getting stared

### Tensors

In [2]:
# from __future__ import print_function
import torch

x = torch.rand(5, 3)
print(x)

tensor([[0.3893, 0.4298, 0.6030],
        [0.9913, 0.7243, 0.3279],
        [0.2813, 0.0425, 0.3246],
        [0.6688, 0.0263, 0.7115],
        [0.8539, 0.7296, 0.8299]])


In [3]:
torch.empty(5, 3)

tensor([[2.1833e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 5.0948e-14]])

In [4]:
torch.rand(3, 3)

tensor([[0.8364, 0.9508, 0.8205],
        [0.6163, 0.7690, 0.8439],
        [0.9222, 0.2829, 0.0864]])

In [5]:
torch.zeros(3, 3, dtype=torch.int)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [6]:
x = torch.tensor([1, 2.3])

In [7]:
x = x.new_ones(4, 3, dtype=torch.int)
print(x)

y = torch.randn_like(x, dtype=torch.float)
print(y)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
tensor([[-1.0790, -0.5086, -1.2842],
        [-1.4947,  1.3933,  1.5676],
        [-0.4340, -0.0876, -0.3106],
        [ 1.5105, -0.6886,  0.2189]])


In [8]:
print(y.size())

torch.Size([4, 3])


### Operations

In [9]:
print(x+y)

tensor([[-0.0790,  0.4914, -0.2842],
        [-0.4947,  2.3933,  2.5676],
        [ 0.5660,  0.9124,  0.6894],
        [ 2.5105,  0.3114,  1.2189]])


In [10]:
torch.add(x, y)

tensor([[-0.0790,  0.4914, -0.2842],
        [-0.4947,  2.3933,  2.5676],
        [ 0.5660,  0.9124,  0.6894],
        [ 2.5105,  0.3114,  1.2189]])

In [11]:
result = torch.empty(4, 3)

torch.add(x, y, out=result)

print(result)

tensor([[-0.0790,  0.4914, -0.2842],
        [-0.4947,  2.3933,  2.5676],
        [ 0.5660,  0.9124,  0.6894],
        [ 2.5105,  0.3114,  1.2189]])


In [12]:
y.add_(x)
print(y)

tensor([[-0.0790,  0.4914, -0.2842],
        [-0.4947,  2.3933,  2.5676],
        [ 0.5660,  0.9124,  0.6894],
        [ 2.5105,  0.3114,  1.2189]])


In [13]:
y[:1, :2]

tensor([[-0.0790,  0.4914]])

In [14]:
x = torch.rand(3, 3)
y = x.view(9)
z = x.view(3, -1)

print(x.size(), y.size(), z.size())

torch.Size([3, 3]) torch.Size([9]) torch.Size([3, 3])


In [15]:
x = torch.rand(1)
print(x.item())

0.24317604303359985


## NumPy Bridge

### Converting a Torch Tensor to a Numpy Array

In [16]:
x = torch.ones(4)

print(x)

tensor([1., 1., 1., 1.])


In [18]:
y = x.numpy()

print(y)

[1. 1. 1. 1.]


In [19]:
x.add_(2)

print(x)
print(y)

tensor([3., 3., 3., 3.])
[3. 3. 3. 3.]


### Converting Numpy Array to Torch Tensor

In [22]:
import numpy as np

x = np.ones((2, 2))
y = torch.from_numpy(x)
np.add(x, 1, out = x)

print(x)
print(y)

[[2. 2.]
 [2. 2.]]
tensor([[2., 2.],
        [2., 2.]], dtype=torch.float64)


### CUDA Tensors

In [26]:
torch.cuda.is_available()
if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.rand(2, 2)
  y = torch.ones_like(x, device=device)
  x = x.to(device)
  z = x + y
  
  print(z)
  print(z.to('cpu', torch.int))

tensor([[1.1383, 1.2715],
        [1.5521, 1.4691]], device='cuda:0')
tensor([[1, 1],
        [1, 1]], dtype=torch.int32)
